### ISSUE TITLE
大佬，挂好像被封了

### ISSUE THREAD

**Issue by WLH666666Wang** [Alivon/Panda-Learning#104]
出现如楼下的一系列错误，而且后台分值的分布也改了，期望大佬能够解决

**Comment by liuhaiyangliuhaiyang** [comment]
我感觉是分值变了，所以程序出问题了，

**Comment by Going2333** [comment]
强国好像改版了，软件用不了，大佬有空的话看一下呗

**Comment by Going2333** [comment]
我卢本伟没有开挂！！

好像走错片场了...

**Comment by noway2014** [comment]
不再总排名了。感觉是正确的调整，因为这个排名，产生神人公愤的。没有排名，也没有必要刷了

**Comment by WLH666666Wang** [comment]
> 不再总排名了。感觉是正确的调整，因为这个排名，产生神人公愤的。没有排名，也没有必要刷了

但是还有每日分数啊，我们就是看这个的😂

**Comment by cznnfuture** [comment]
昨天开始就错误了，是被封了么？

**Comment by poplong2** [comment]
> > 不再总排名了。感觉是正确的调整，因为这个排名，产生神人公愤的。没有排名，也没有必要刷了
> 
> 但是还有每日分数啊，我们就是看这个的😂

因为各单位间有排名，要是你们单位分数垫底，你们的领导会被批评，所以他才对你每日分数有要求。如果没有排名了，他就没这个压力，他可能就不用在意你们的每日积分了。

**Comment by Alivon** [comment]
已经 紧急修复
