### ISSUE TITLE
Devtools提示platform_sensor_reader_win.cc（242）

### ISSUE THREAD

**Issue by tefiszx** [Alivon/Panda-Learning#11]
登陆成功，即将开始自动学习
阅读文章得分6分/6分，需要再学习0篇文章
观看视频得分4分/6分，需要再学习2个视频
文章学习时长得分2分/8分，需要再学习24分钟文章
视频学习市场得分0分/10分，需要再学习50分钟视频
历史学习记录读取成功
正在多线程学习中，文章剩余1440秒
DevTools listening on ws://127.0.0.1:50182/devtools/browser/9a09482f-cc3a-44f6-ae4a-4cf9455bdc47
正在多线程学习中，文章剩余1434秒

==============================
正在多线程学习中，视频剩余2999秒[6508:10252:0315/085021.918:**ERROR:platform_sensor_reader_win.cc(242)] NOT IMPLEMENTED**
正在多线程学习中，视频剩余2610秒

**Comment by Alivon** [comment]
> 登陆成功，即将开始自动学习
> 阅读文章得分6分/6分，需要再学习0篇文章
> 观看视频得分4分/6分，需要再学习2个视频
> 文章学习时长得分2分/8分，需要再学习24分钟文章
> 视频学习市场得分0分/10分，需要再学习50分钟视频
> 历史学习记录读取成功
> 正在多线程学习中，文章剩余1440秒
> DevTools listening on ws://127.0.0.1:50182/devtools/browser/9a09482f-cc3a-44f6-ae4a-4cf9455bdc47
> 正在多线程学习中，文章剩余1434秒
> 
> ==============================
> 正在多线程学习中，视频剩余2999秒[6508:10252:0315/085021.918:**ERROR:platform_sensor_reader_win.cc(242)] NOT IMPLEMENTED**
> 正在多线程学习中，视频剩余2610秒

不影响使用

**Comment by noway2014** [comment]
解决了win7使用问题了吗？等，急

**Comment by Alivon** [comment]
> 解决了win7使用问题了吗？等，急

我刚下载win7 32位的  等下打包好上传就可以使用了

**Comment by Alivon** [comment]
> 解决了win7使用问题了吗？等，急

已跟新 @
