### ISSUE TITLE
感谢作者，请问能否在后期添加海外手机号登陆功能？

### ISSUE THREAD

**Issue by shadow-fight** [Alivon/Panda-Learning#118]
海外的人并不想手机号被泄露，能否有一个选择登陆地区的功能，在钉钉的页面是个下拉框，修改起来应该不是很困难

**Comment by Liridice** [comment]
这个你应该提交给学习强国的开发者

**Comment by Alivon** [comment]
无法实现  
无意义issues 关闭

**Comment by shadow-fight** [comment]
本身钉钉的登录界面是有国家选择的，软件本身可以使用国外手机号登陆，隔壁的软件弹出登录界面后可以自己手动选择，这个不需要学习强国的更新，应该是在操作自动登陆的.py文件中增加一个选择
