### ISSUE TITLE
[Bug Report]The remaining time of learning cannot be displayed correctly when < 100s

### ISSUE THREAD

**Issue by Msopopop** [Alivon/Panda-Learning#125]
**What steps will reproduce the problem?** 
1. Run the main program;
2. Occurs naturally. (occurs every time)

**What is the expected output? What do you see instead?** 
The display shall be 
```
100...99...98
```
rather than
```
100...990...980
```

**What version of the product are you using? On what operating system?** 
Using Windows 10 1809 x64 (17763.379), version of Panda-Learning is 2.2.

**Please see the gif image as shown for further information.**
![b](https://user-images.githubusercontent.com/29355936/55249107-4ba96a00-5286-11e9-9b08-8ce515aa865a.gif)

**Comment by Alivon** [comment]
注意到了 ，会排查一下

**Comment by Alivon** [comment]
问题原因是多的那个0是，文章最后剩余的0秒

**Comment by Msopopop** [comment]
Problem solved.
Thanks for dealing!
If you can, have you considered open donation channels(such as Alipay QR code, WeChat QR code, PayPal link, etc)?
This software helped me a lot, and I think it's the best way for me to show my thanks.

**Comment by Alivon** [comment]
心领了
