### ISSUE TITLE
V2.3 win10x64 文章和视频学习数量不增加

### ISSUE THREAD

**Issue by shadiaojiuguo** [Alivon/Panda-Learning#136]
使用时 文章和视频学习时长已经完成，但是文章和视频学习数量不增加，使用show参数前台查看，网页显示无问题，但是上面红色横幅显示不完整。请大佬帮忙解决。

**Comment by Alivon** [comment]
让他继续运行或者尝试修改user下a_log和v_log

**Comment by shadiaojiuguo** [comment]
谢谢大佬回复，修改a_log和v_log值后正常。
