### ISSUE TITLE
MacOS版本这周会上吗？

### ISSUE THREAD

**Issue by lenzwu** [Alivon/Panda-Learning#16]
特别好用的学习软件，家里没有windows电脑，希望能开发一个MacOS版本

**Comment by Alivon** [comment]
> 特别好用的学习软件，家里没有windows电脑，希望能开发一个MacOS版本

谢谢使用，建议先用mac下虚拟机代替，mac应该会在这周内更新

**Comment by lenzwu** [comment]
> > 特别好用的学习软件，家里没有windows电脑，希望能开发一个MacOS版本
> 
> 谢谢使用，建议先用mac下虚拟机代替，mac应该会在这周内更新

好的，给你点赞！

**Comment by Alivon** [comment]
> > > 特别好用的学习软件，家里没有windows电脑，希望能开发一个MacOS版本
> > 
> > 
> > 谢谢使用，建议先用mac下虚拟机代替，mac应该会在这周内更新
> 
> 好的，给你点赞！

mac已跟新，有个坑，搞了半天

**Comment by lenzwu** [comment]
> > > > 特别好用的学习软件，家里没有windows电脑，希望能开发一个MacOS版本
> > > 
> > > 
> > > 谢谢使用，建议先用mac下虚拟机代替，mac应该会在这周内更新
> > 
> > 
> > 好的，给你点赞！
> 
> mac已跟新，有个坑，搞了半天

🤙🏻🤙🏻🤙🏻

**Comment by lenzwu** [comment]
在终端输入：yournameMac:pandalearning-mac yourname$
显示：command not found

**Comment by Alivon** [comment]
> 在终端输入：yournameMac:pandalearning-mac yourname$
> 显示：command not found

不是这样输入 请仔细看下说明

**Comment by lenzwu** [comment]
> > 在终端输入：yournameMac:pandalearning-mac yourname$
> > 显示：command not found
> 
> 不是这样输入 请仔细看下说明

解压文件放在哪有讲究吗？

**Comment by Alivon** [comment]
> > > 在终端输入：yournameMac:pandalearning-mac yourname$
> > > 显示：command not found
> > 
> > 
> > 不是这样输入 请仔细看下说明
> 
> 解压文件放在哪有讲究吗？

没有 yourname就是你的mac 用户名  在解压文件夹打开终端

**Comment by lenzwu** [comment]
原来是在解压文件夹打开终端，划重点😂 现在搞定了，多谢！
