### ISSUE TITLE
请问Linux服务器上也能部署吗

### ISSUE THREAD

**Issue by MQL9011** [Alivon/Panda-Learning#161]
Linux服务器上是否可以部署， 没有图形界面，没有Chrome 请问能否部署运行？

**Comment by zyftank** [comment]
可以，参照树莓派版说明。

**Comment by bdya2005** [comment]
在GCP主机上，debian 9下测试成功，可每天自动按时学习，真香。

**Comment by failsray** [comment]
借楼同问，求哪位大神发一个傻瓜式教程

**Comment by gantrylueng** [comment]
> 在GCP主机上，debian 9下测试成功，可每天自动按时学习，真香。

我的也是debian 9，跪求傻瓜教程。我要就是像你一样的功能，每天零时开始学习。
先谢谢了。这个可以写成个大贴呢！！

**Comment by gantrylueng** [comment]
> 在GCP主机上，debian 9下测试成功，可每天自动按时学习，真香。

今天下午按树莓派的说明，安装了一下，各种“依赖”搞不定。虚拟机用的是x86_64位的系统debian9。

> 可以，参照树莓派版说明。

**Comment by zyftank** [comment]
@gantrylueng 你在denian上装树莓派的程序？我没试过，debian版本换镜像源，自己安装chrome和chromedriver，xvfb，源码等明天给你链接，自己去调试。最好用源码，出问题自己随时可以改。

**Comment by gantrylueng** [comment]
> @gantrylueng 你在denian上装树莓派的程序？我没试过，debian版本换镜像源，自己安装chrome和chromedriver，xvfb，源码等明天给你链接，自己去调试。最好用源码，出问题自己随时可以改。

我也学过一点linux。不是装树莓派的程序。是按它的方法，我去了清华那里把软件都下载了，回来装，也是先装chrome，后chromedriver，但是出现“依赖问题”

**Comment by zyftank** [comment]
我装的时候也是存在各种依赖问题，不过百度了一下，一个指令解决了问题。

**Comment by zyftank** [comment]
debian真的没用过，不过建议换换其他源试试，自己找找适合的程序。反正就是那几个软件，装好就可以用，我节后传个源码，有问题自己改代码方便一点。

**Comment by ZhaoqiangCn** [comment]
> 在GCP主机上，debian 9下测试成功，可每天自动按时学习，真香。

你好，可否写一个简要的教程？ 我也是GCP debian

**Comment by MQL9011** [comment]
VPS Ubuntu求

**Comment by EdwardZhu91** [comment]
> @gantrylueng 你在denian上装树莓派的程序？我没试过，debian版本换镜像源，自己安装chrome和chromedriver，xvfb，源码等明天给你链接，自己去调试。最好用源码，出问题自己随时可以改。

我Ubuntu18在运行程序的时候老是提示-bash: ./pandalearning-pi: cannot execute binary file: Exec format error
直接运行源码嘛，又有好多引用又没有，大佬指路啊

**Comment by zyftank** [comment]
建议linux系统直接运行源代码，ubuntu很好搞定，只要安装好软件，缺少python的引用包，可以使用pip安装，很方便，而且ubuntu安装出错的机会很少，系统最好是64位的。

**Comment by ZhaoqiangCn** [comment]
> > 在GCP主机上，debian 9下测试成功，可每天自动按时学习，真香。
> 
> 你好，可否写一个简要的教程？ 我也是GCP debian

研究出来了，GCP Debian9 下 根据博主树莓派的方法成功运行。

**Comment by ZhaoqiangCn** [comment]
有一个问题请教一下各位大佬，，由于部署在GCP国外节点，会不会被侦测到登陆IP非国内IP呢？

**Comment by mazda1152** [comment]
> 有一个问题请教一下各位大佬，，由于部署在GCP国外节点，会不会被侦测到登陆IP非国内IP呢？

你的担心很有道理

**Comment by baoang** [comment]
> > 有一个问题请教一下各位大佬，，由于部署在GCP国外节点，会不会被侦测到登陆IP非国内IP呢？
> 
> 你的担心很有道理

难道海外就没有爱国华人对这个软件喜爱到不天天学习就不行的地步吗？理论上，非国内登录的IP也可能是使馆工作人员在学习。

**Comment by MQL9011** [comment]
可以部署了
