### ISSUE TITLE
关于保存账号后的闪退问题

### ISSUE THREAD

**Issue by hahahaozi** [Alivon/Panda-Learning#167]
`第一次选择了通过钉钉登陆保存登录信息后第二次打开，登陆闪退，只能卸载重装。望解决。```

**Comment by Alivon** [comment]
请在仔细阅读使用说明的情况下，确保操作正确。提问请说明你的操作系统及环境，我刚才在win7 32位系统测试了下，没有问题，看看是不是系统缺失Visual C++ Redistributable for Visual Studio 2015情况，页面有提供下载
