### ISSUE TITLE
今天使用时突然报错，无法登录

### ISSUE THREAD

**Issue by fengyu397** [Alivon/Panda-Learning#169]
今天使用的时候，用二维码登陆，显示：

无法访问此网站 网址为 https://pc-api.xuexi.cn/open/api/sns/callback?code=749f2d903a65309a9a0ce6de9894f7b5&state=1554611998137 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_NAME_RESOLUTION_FAILED

**Comment by Alivon** [comment]
经测试可以正常打开
