### ISSUE TITLE
第四个参数问题

### ISSUE THREAD

**Issue by chenzhiwei-github** [Alivon/Panda-Learning#179]
以前好像是关闭控制台窗口，现在变成了关机，有个bug就是我设置300秒关机，当我不想让他关机，我把控制台关闭了，可是300秒后还是执行了自动关机，建议几秒后自动关机和关闭控制台可以分开设置，因为我是用脚本自动运行，我只想让他刷完分自动关闭控制台，不想让关机

**Comment by pjx1688** [comment]
我也一样，不要设置后面的关机数字，但要重启电脑生效，我现在的问题是，学习完成，不会自动关闭窗口了

**Comment by wqh966** [comment]
请仔细查看说明文件，第四个参数是设置自动关机命令，自动关闭控制台命令无需设置，默认10分钟后自动关闭

**Comment by herocspx** [comment]
原来是学习完成30分钟后自动关闭程序窗口，现在不行了吗？？

**Comment by chenzhiwei-github** [comment]
> 请仔细查看说明文件，第四个参数是设置自动关机命令，自动关闭控制台命令无需设置，默认10分钟后自动关闭

前几个版本第四个参数就是设置关闭窗口的倒数哦，默认10分钟关闭控制台没有打印提示，说明文档也没注释，这个还真不知道呢
