### ISSUE TITLE
请问开发者，有没有那个版本可以在树莓派上面运行的？

### ISSUE THREAD

**Issue by noway2014** [Alivon/Panda-Learning#19]
树莓派就是rasapberry pi

**Comment by Alivon** [comment]
公开的源码换成无头浏览器即可在vps开发板等环境运行

**Comment by noway2014** [comment]
如果有一个程序就好了

**Comment by noway2014** [comment]
經過測試，用
virtualenv 把 selenium 装好，直接在樹莓派上面跑了，但是以後作者更新的話不知道如何更新？能否直接替換某一個文件就可以更新呢？

**Comment by Alivon** [comment]
> 經過測試，用
> virtualenv 把 selenium 装好，直接在樹莓派上面跑了，但是以後作者更新的話不知道如何更新？能否直接替換某一個文件就可以更新呢？

@noway2014 源码更改chromedriver路径就可以了

**Comment by cxl008** [comment]
@noway2014  请问你在树莓派上 chromedriver 用的啥参数，还是在pi上装了个chrome？
