### ISSUE TITLE
登陆错误

### ISSUE THREAD

**Issue by elleys** [Alivon/Panda-Learning#219]
etc_peer_connection_handler.cc(1201) fail to parse sessiondescription .a=msid :missing track in msid attribute

**Comment by fuckthegit** [comment]
同错误：
```
[0411/232821.818:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
Traceback (most recent call last):
  File "pandalearning.py", line 181, in <module>
  File "pandalearning.py", line 49, in show_score
  File "pdlearn\score.py", line 14, in get_score
  File "pdlearn\score.py", line 14, in <listcomp>
TypeError: string indices must be integers
[7988] Failed to execute script pandalearning
```

**Comment by GPPyeye** [comment]
> 同错误：
> 
> ```
> [0411/232821.818:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
> Traceback (most recent call last):
>   File "pandalearning.py", line 181, in <module>
>   File "pandalearning.py", line 49, in show_score
>   File "pdlearn\score.py", line 14, in get_score
>   File "pdlearn\score.py", line 14, in <listcomp>
> TypeError: string indices must be integers
> [7988] Failed to execute script pandalearning
> ```

同错误，看来后台又升级了

**Comment by fuckthegit** [comment]
> > 同错误：
> > ```
> > [0411/232821.818:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
> > Traceback (most recent call last):
> >   File "pandalearning.py", line 181, in <module>
> >   File "pandalearning.py", line 49, in show_score
> >   File "pdlearn\score.py", line 14, in get_score
> >   File "pdlearn\score.py", line 14, in <listcomp>
> > TypeError: string indices must be integers
> > [7988] Failed to execute script pandalearning
> > ```
> 
> 同错误，看来后台又升级了

应该是，也不知道怎么个情况

**Comment by pacocai** [comment]
一样！今天登陆就会出现这个异常！

**Comment by lorange** [comment]
同错误

**Comment by Lxxsss** [comment]
我也是，什么情况？需要更新一下嘛？

**Comment by bonww** [comment]
> > > 同错误：
> > > ```
> > > [0411/232821.818:ERROR:rtc_peer_connection_handler.cc(1201)] Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.
> > > Traceback (most recent call last):
> > >   File "pandalearning.py", line 181, in <module>
> > >   File "pandalearning.py", line 49, in show_score
> > >   File "pdlearn\score.py", line 14, in get_score
> > >   File "pdlearn\score.py", line 14, in <listcomp>
> > > TypeError: string indices must be integers
> > > [7988] Failed to execute script pandalearning
> > > ```
> > 
> > 
> > 同错误，看来后台又升级了
> 
> 应该是，也不知道怎么个情况

+1

**Comment by wdmb123** [comment]
修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

**Comment by Going2333** [comment]
> 修改score.py第十三行为each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]即可解决

windows的要怎么破，求大神...
