### ISSUE TITLE
2.4版本 show_score出错了

### ISSUE THREAD

**Issue by MQL9011** [Alivon/Panda-Learning#222]
![image](https://user-images.githubusercontent.com/11871158/56002851-a1562b80-5cf6-11e9-81a2-2f3774571cf4.png)

**Comment by tuutoo** [comment]
一样的错误，应该是强国那边更新了什么了。

**Comment by yg1031** [comment]
改一下代码，score.py中，将
each = json.loads(each, encoding="utf8")["data"]
改为：
each = json.loads(each, encoding="utf8")["data"]["dayScoreDtos"]

**Comment by Alivon** [comment]
已修复
