### ISSUE TITLE
出现TypeError,是什么情况？

### ISSUE THREAD

**Issue by kentcc88** [Alivon/Panda-Learning#229]
[出现TypeError错误，string indices must be integers "9680" Failed to execute script pandaleaning](https://github.com/kentcc88/uploadimages/blob/master/2019-04-12_102151.png)

**Comment by dynamohuang** [comment]
这里兄dei https://github.com/Alivon/Panda-Learning/issues/223

**Comment by Sunxb** [comment]
还是用代码自己跑灵活一下啊 ~

**Comment by suqianstone** [comment]
自己编译一下，轻松自在

**Comment by Alivon** [comment]
已修复
