### ISSUE TITLE
保存钉钉账号不支持非+86的手机号吗

### ISSUE THREAD

**Issue by XiaoPika** [Alivon/Panda-Learning#238]
学习强国绑定的是一个美国 +1 的手机号，一直没法保存：

![image](https://user-images.githubusercontent.com/10910848/56046574-1fa5e280-5d76-11e9-8415-c0d00bad44b3.png)

**Comment by Alivon** [comment]
手动修改user文件夹dingding文件吧 我设置了手机号输入验证

**Comment by XiaoPika** [comment]
> 手动修改user文件夹dingding文件吧 我设置了手机号输入验证

改成 +1xxx 、 01xxx 、1xxx 、 xxx 均不行，我在钉钉登录的时候需要先点击 +86 ，selected +1 后才行，程序是不是默认不支持这一步？

**Comment by XiaoPika** [comment]
> 手动修改user文件夹dingding文件吧 我设置了手机号输入验证
![image](https://user-images.githubusercontent.com/10910848/56075408-114adb80-5df5-11e9-9d5a-0baea68f42c1.png)

**Comment by jxzzy** [comment]
你都能办那样的卡了   还学习这个干什么? 
你真的那么爱学习还是卧底来的?

**Comment by Alivon** [comment]
不支持外国手机，也不太想调整支持外国手机，实在想用，先登陆国内手机帐户，然后更改user文件夹里面账号信息

**Comment by XiaoPika** [comment]
> 不支持外国手机，也不太想调整支持外国手机，实在想用，先登陆国内手机帐户，然后更改user文件夹里面账号信息

明白，暂时借了同事的+86手机号绑定了。
