### ISSUE TITLE
Mac下出错

### ISSUE THREAD

**Issue by HelloSweet** [Alivon/Panda-Learning#242]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/12152947/56075734-c2537500-5df9-11e9-890e-53f123780500.png">

**Comment by fuckthegit** [comment]
pandalearning.py 所在目录没有chrome driver吧？另外安装了selenium和requests没有啊老哥

**Comment by Alivon** [comment]
不能双击运行哦，mac下要用终端运行

**Comment by HelloSweet** [comment]
> pandalearning.py 所在目录没有chrome driver吧？另外安装了selenium和requests没有啊老哥

装了requests，另一个好像木有。。。

**Comment by HelloSweet** [comment]
> 不能双击运行哦，mac下要用终端运行

还是不得行，命令行到panda学习到文件夹，然后执行，还是错误

**Comment by Alivon** [comment]
> 不得行，命令行到panda学习到文件夹，然后执

源码运行 除了requests 还要安装selenium

**Comment by sbw983** [comment]
chrome driver也得复制到同一目录下才能直接从源码执行

**Comment by HelloSweet** [comment]
> > 不得行，命令行到panda学习到文件夹，然后执
> 
> 源码运行 除了requests 还要安装selenium

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/12152947/56089625-6572c000-5ec8-11e9-9043-0cb4da745e66.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/12152947/56089629-6e639180-5ec8-11e9-9e20-644ed1e381e1.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/12152947/56089642-9fdc5d00-5ec8-11e9-8e11-5c2a6860de70.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/12152947/56089639-99e67c00-5ec8-11e9-9160-563b63b2c995.png">

还是不行，阿西吧，是不是anaconda的问题，两个文件我是在一个文件夹里面放着的

**Comment by Alivon** [comment]
你那个报错就是路径问题，用打包好的不需要自己下环境，直接终端运行就行了。。你搞复杂了

**Comment by HelloSweet** [comment]
> 你那个报错就是路径问题，用打包好的不需要自己下环境，直接终端运行就行了。。你搞复杂了

我也看到是路径问题了，但是路径我检查好多次了木有问题。。。

**Comment by sbw983** [comment]
> > > 不得行，命令行到panda学习到文件夹，然后执
> > 
> > 
> > 源码运行 除了requests 还要安装selenium
> 
> <img alt="image" width="1077" src="https://user-images.githubusercontent.com/12152947/56089625-6572c000-5ec8-11e9-9043-0cb4da745e66.png">
> 
> <img alt="image" width="582" src="https://user-images.githubusercontent.com/12152947/56089629-6e639180-5ec8-11e9-9e20-644ed1e381e1.png">
> 
> <img alt="image" width="634" src="https://user-images.githubusercontent.com/12152947/56089642-9fdc5d00-5ec8-11e9-8e11-5c2a6860de70.png">
> 
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/12152947/56089639-99e67c00-5ec8-11e9-9160-563b63b2c995.png">
> 
> 还是不行，阿西吧，是不是anaconda的问题，两个文件我是在一个文件夹里面放着的

有没有给chromedriver和pandalearning加上可执行权限？

**Comment by HelloSweet** [comment]
> > > > 不得行，命令行到panda学习到文件夹，然后执
> > > 
> > > 
> > > 源码运行 除了requests 还要安装selenium
> > 
> > 
> > <img alt="image" width="1077" src="https://user-images.githubusercontent.com/12152947/56089625-6572c000-5ec8-11e9-9043-0cb4da745e66.png">
> > <img alt="image" width="582" src="https://user-images.githubusercontent.com/12152947/56089629-6e639180-5ec8-11e9-9e20-644ed1e381e1.png">
> > <img alt="image" width="634" src="https://user-images.githubusercontent.com/12152947/56089642-9fdc5d00-5ec8-11e9-8e11-5c2a6860de70.png">
> > <img alt="image" width="573" src="https://user-images.githubusercontent.com/12152947/56089639-99e67c00-5ec8-11e9-9160-563b63b2c995.png">
> > 还是不行，阿西吧，是不是anaconda的问题，两个文件我是在一个文件夹里面放着的
> 
> 有没有给chromedriver和pandalearning加上可执行权限？

应该不是，pandalearning可以执行，但是找不到chromedriver

**Comment by Alivon** [comment]
#256
