### ISSUE TITLE
钉钉登录的接口好像被取消了

### ISSUE THREAD

**Issue by asdqwe111** [Alivon/Panda-Learning#251]
下午刚刚更新，扫码目前可以登录，账号密码好像不行了
![77106c6e4bddfaa855f41c2804ff556](https://user-images.githubusercontent.com/48905248/56131163-4a33ad80-5fb9-11e9-8285-7ae55f02a6f3.png)

**Comment by nillsfire** [comment]
> 下午刚刚更新，扫码目前可以登录，账号密码好像不行了

刚运行，可以的。

**Comment by asdqwe111** [comment]
> > 下午刚刚更新，扫码目前可以登录，账号密码好像不行了
> 
> 刚运行，可以的。

win7 64?

**Comment by herocspx** [comment]
没有问题，一切正常。

**Comment by cxl008** [comment]
需要填写验证码了

**Comment by Alivon** [comment]
可以运行
