### ISSUE TITLE
运行正常，但是不加分。

### ISSUE THREAD

**Issue by Raistlin-1** [Alivon/Panda-Learning#280]
<img width="732" alt="捕获" src="https://user-images.githubusercontent.com/22558470/56589687-52729500-6618-11e9-9cbd-6f713c5713b8.PNG">

**Comment by zhaoml529** [comment]
我也是不加分，通过钉钉授权页面登录的账号可以显示加分后的信息(授权连接：https://login.dingtalk.com/login/index.htm?goto=https%3A%2F%2Foapi.dingtalk.com%2Fconnect%2Foauth2%2Fsns_authorize%3Fappid%3Ddingoankubyrfkttorhpou%26response_type%3Dcode%26scope%3Dsnsapi_login%26redirect_uri%3Dhttps%3A%2F%2Fpc-api.xuexi.cn%2Fopen%2Fapi%2Fsns%2Fcallback)。但是在app上用相同账号登录就没有积分，感觉像是两个账号。这个是什么问题？

**Comment by Melissayuxi** [comment]
这种情况暂时只能在是否保存账号信息的时候输入n，通过扫码登录解决。

**Comment by Raistlin-1** [comment]
扫码登陆能解决，多谢
