### ISSUE TITLE
mac版mydrives相关解答

### ISSUE THREAD

**Issue by kalasusen** [Alivon/Panda-Learning#287]
mac存在mydrives错误的童鞋，请下载相应chromedriver，放入/usr/bin/ 即可。如权限不足，重启电脑C+R，终端，csrutil disable ，重启即可。
顺便问一下，MAC如何加入参数

**Comment by Alivon** [comment]
我知道mac下也有同linux的 crontab等自动执行任务 mac我不会用，但是肯定是能够加参数的

**Comment by kalasusen** [comment]
> 我知道mac下也有同linux的 crontab等自动执行任务 mac我不会用，但是肯定是能够加参数的

mac下保存账号登录之后读取不到账号信息，且学习之后不计分。已修改2个log文件

**Comment by kalasusen** [comment]
> > 我知道mac下也有同linux的crontab等自动执行任务mac我不会用，但是肯定是能够加参数的
> 
> MAC下保存账号登录之后读取不到账号信息，且学习之后不计分。已修改2个日志文件

已解决，不支持mac最新版chrome，更换旧版即可

**Comment by chechengpeng** [comment]
不需要降级 chrome ，chrome 升级之后，只需要下载相应的 chromedrive 文件，覆盖pandalearning_macos 文件夹中的该文件即可
