### ISSUE TITLE
Mac系统 刷分无效 不增加分数

### ISSUE THREAD

**Issue by Lxxsss** [Alivon/Panda-Learning#289]
刷了半天没有进度，是不是被监测到屏蔽了？？？

修改a_log和v_log文件中的数值后，还是一样无效。

![image](https://user-images.githubusercontent.com/11531863/56779764-135a6480-680f-11e9-873a-1aa8e4d16761.png)

**Comment by Lxxsss** [comment]
@Alivon

**Comment by Alivon** [comment]
这边一切正常，暂无其他人反馈相同问题

**Comment by BITDM** [comment]
有同样问题

**Comment by AllrightChou** [comment]
有同样问题+1

**Comment by AllrightChou** [comment]
> 这边一切正常，暂无其他人反馈相同问题

<img width="825" alt="QQ20190427-191410@2x" src="https://user-images.githubusercontent.com/40154364/56848950-c5358600-6920-11e9-9b08-4f7f8fd818b4.png">

**Comment by xzdbadboy** [comment]
<img width="495" alt="屏幕快照 2019-04-27 下午10 54 24" src="https://user-images.githubusercontent.com/30276489/56851256-7ea35400-693f-11e9-8491-1dc5c1ed7233.png">
Mac 不加分数。

**Comment by Lxxsss** [comment]
@Alivon 感觉像是，刷过分的文章和视频，不再增加积分，才导致的刷分无效。

**Comment by lvminghan44** [comment]
还是没有解决吗这个

**Comment by JunIce** [comment]
+1

**Comment by nukaten** [comment]
Ubuntu分数正常，Mac分数不增加

**Comment by heTaoEvo** [comment]
我更新chromedriver之后遇到同样问题

**Comment by lemonzlm** [comment]
chrome 更新到了74就出现了这个问题。

**Comment by Lxxsss** [comment]
好像是的，我也是更新之后有问题的

**Comment by Lxxsss** [comment]
降版本后，可以正常使用了

**Comment by heTaoEvo** [comment]
> 降版本后，可以正常使用了

降chrome版本?

**Comment by Lxxsss** [comment]
> > 降版本后，可以正常使用了
> 
> 降chrome版本?

是的

**Comment by H2OESSENCE** [comment]
same issue
