### ISSUE TITLE
get_video_links获取失败

### ISSUE THREAD

**Issue by wisdog** [Alivon/Panda-Learning#291]
我有另外两台电脑使用没有任何问题。
前天科室的电脑xp升级成win7，发现一个问题：
使用强国app扫码登录可以刷分，可是使用钉钉账号登录以后显示
get_video_links获取失败，然后闪退。
真是奇怪，请教各位大侠，怎么解决？

**Comment by Alivon** [comment]
很大可能是装了虚拟机，查询相关issue
