### ISSUE TITLE
只使用了两个线程吗？

### ISSUE THREAD

**Issue by Fxxk-XueXiQiangGuo** [Alivon/Panda-Learning#3]
```python
t2 = Thread(target=learn_video, args=(cookies, videonum, videotime * 60, log, video))
t2.start()
learn_article(readnum, readtime * 60, log, article)
t2.join()
```

**Comment by Alivon** [comment]
是的  而且没有加入活跃时间减少机制， 活跃时间应该还能减少一倍学习时间

**Comment by Fxxk-XueXiQiangGuo** [comment]
另外说一下，用python打包成的exe逆向工程很容易，建议直接开源。

**Comment by Alivon** [comment]
> 另外说一下，用python打包成的exe逆向工程很容易，建议直接开源。
谢谢提醒   打包只是为了方便 使用者不敲python命令

**Comment by poplong2** [comment]
> 是的 而且没有加入活跃时间减少机制， 活跃时间应该还能减少一倍学习时间

我昨天看到剩余时间减到零之后，还会继续-1秒、-2秒、-3秒……无限地减下去。

**Comment by Alivon** [comment]
> > 是的 而且没有加入活跃时间减少机制， 活跃时间应该还能减少一倍学习时间
> 
> 我昨天看到剩余时间减到零之后，还会继续-1秒、-2秒、-3秒……无限地减下去。

这是文章数量已经学完但是时长不够，正常情况 ，不影响使用

**Comment by Alivon** [comment]
> 另外说一下，用python打包成的exe逆向工程很容易，建议直接开源。

已经开源
