### ISSUE TITLE
学习文章视频一直没增加分数解决办法

### ISSUE THREAD

**Issue by yanhcl** [Alivon/Panda-Learning#307]
5.2号还正常
1、5.3号晚上开始登陆成功后，启动阅读会要好多时间.
2、文章和视频的时长都正常，但是阅读和视频永远都是0这里的6分永远没有完成，程序就一直这样死循环下去了。

**Comment by yanhcl** [comment]
后来发现运行2小时12分钟才完成，会不会和之前阅读不会算分，一直往后循环到没有阅读过的才算。

**Comment by G3boy** [comment]
a_log文件数值加大点就好了

**Comment by Alivon** [comment]
应该是默认阅读都学习的你以前学过的了，所以它会一直遍历新的文章，标题帮你改了。还有 请先查看说明和其他issues

**Comment by hongm328** [comment]
a_log和v_log增加到一定数值（时间一长，可能超过文章和视频数量）就会出错，应该能加上自动重置功能！

**Comment by Alivon** [comment]
> a_log和v_log增加到一定数值（时间一长，可能超过文章和视频数量）就会出错，应该能加上自动重置功能！

几万条文章视频，学完至少10年左右，而且内容还在增加，😀

**Comment by Alivon** [comment]
> > a_log和v_log增加到一定数值（时间一长，可能超过文章和视频数量）就会出错，应该能加上自动重置功能！
> 
> 几万条文章视频，学完至少10年以上，而且内容还在增加，😀
