### ISSUE TITLE
使用随机UA有被检测风险

### ISSUE THREAD

**Issue by github-superadmin** [Alivon/Panda-Learning#309]
![image](https://user-images.githubusercontent.com/50284425/57188770-b2314000-6f36-11e9-844f-2641f1cc6a59.png)
每次运行时会随机UA，但这些UA均过老，chrome19/20版本已经是老古董，必想没人会每天换电脑和浏览器学习吧，可针对此进行检测。
以上仅代表个人观点。

**Comment by github-superadmin** [comment]
如果可能，建议作者加入自定义UA功能

**Comment by jxzzy** [comment]
全国上亿人，估计阿里不会专门对这个跟踪分析

**Comment by Alivon** [comment]
使用强国年轻人反而不多，所以老式浏览器很正常，且不担心检测问题，如果下版本更新可以加上自定义ua

**Comment by Phishion** [comment]
随机 UA 没问题，关键如果每次启动 UA 都不一样也有问题吧，谁闲着没事整天换浏览器，应该是每个账号对应一个固定的 UA
