### ISSUE TITLE
程序正常,但是不加分是怎么回事啊?

### ISSUE THREAD

**Issue by Loren1994** [Alivon/Panda-Learning#311]
程序正常,但是不加分是怎么回事啊?今天突然这样了,之前一直好好的

**Comment by Alivon** [comment]
尝试更改用户目录下log数值

**Comment by nukaten** [comment]
a_log v_log修改了都没啥作用

**Comment by Loren1994** [comment]
改a_log v_log数值,删a_log v_log文件都不行...

**Comment by Lxxsss** [comment]
#289

**Comment by H2OESSENCE** [comment]
The same issue, any one can give any solutions?

**Comment by baosage** [comment]
Run normally

**Comment by Loren1994** [comment]
是chrome自动升到74导致的,降回73正常了.
Mac下禁止chrom自动更新的方法:
进入/Library/Google/GoogleSoftwareUpdate目录,删除GoogleSoftwareUpdate.bundle即可.
