### ISSUE TITLE
帐号不关联

### ISSUE THREAD

**Issue by sqreb** [Alivon/Panda-Learning#312]
在脚本pdlearn/score.py 中作者通过如下方法得到当前分数
total = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar).content.decode("utf8")
其中，的到的json文件的userId为用户ID

在使用脚本登录时
sqreb@sqreb:~/github/Panda-Learning/Source Packages$ python3 pandalearning.py sqreb

登陆中...
{"data":{"userId":662693672,"scoreTypeId":0,"scoreTypeName":"总积分","score":25.0,"time":0,"scoreV2":"0"},"message":"OK","code":200,"error":null,"ok":true}
当前学习总积分：25
阅读文章:6/6,观看视频:6/6,登陆:1/1,文章时长:6/6,视频时长:6/6

在浏览器输入相同手机号
{"data":{"userId":151004596001,"scoreTypeId":0,"scoreTypeName":"总积分","score":1.0,"time":0,"scoreV2":"0"},"message":"OK","code":200,"error":null,"ok":true}

可以看到两个userId不相同。使用手机发现分数没有增加。不知道为什么帐号没有关联

Update: 这有可能是新的学习强国帐号和钉钉帐号解绑定的原因，请问有什么方法可以让手机的学习强国进入钉钉的帐号，或者增加学习强国扫码的代码么

Update: 可以不用dingding扫码登录

**Comment by adslhuang** [comment]
这个问题解决了吗？？
