### ISSUE TITLE
如何更新版本

### ISSUE THREAD

**Issue by failsray** [Alivon/Panda-Learning#32]
会自动更新吗？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Alivon** [comment]
> 会自动更新吗？
> 
> Sent from [PPHub](https://itunes.apple.com/cn/app/id1314212521)

重新下载

**Comment by failsray** [comment]
多谢大佬😀
