### ISSUE TITLE
win10 64位 版本信息网络错误

### ISSUE THREAD

**Issue by JerkYang** [Alivon/Panda-Learning#322]
开启： 获取更新信息...

正在联网获取更新信息...
读取用户信息成功

DevTools listening on ws://127.0.0.1:1513/devtools/browser/5b598b60-4a3c-40d9-8302-9dcd615866c6
登陆中...
当前学习总积分：2693
阅读文章:0/6,观看视频:0/6,登陆:0/1,文章时长:0/6,视频时长:0/6
开启： 文章学习
开启： 视频学习

DevTools listening on ws://127.0.0.1:1603/devtools/browser/a01f70e9-ff36-42cb-a7d0-2749b2e33646

DevTools listening on ws://127.0.0.1:1604/devtools/browser/6687e39a-19e0-48c9-b918-8a5a54b8f7df
版本信息网络错误

**Comment by sutong666** [comment]
我也遇到了这个问题

**Comment by Alivon** [comment]
网络问题，能继续学习可以忽略

**Comment by yemaoxingtianxia** [comment]
> 网络问题，能继续学习可以忽略

我的不能继续学习了，上来就报错是版本信息网络错误，连用户名都还没登录~

**Comment by pan1520** [comment]
网络错误，打开软件登录自动退出
