### ISSUE TITLE
建议增加学习完毕弹窗提示

### ISSUE THREAD

**Issue by yaohunzhanyue** [Alivon/Panda-Learning#327]
本人在windows上后台定时运行bat文件，但是这样就不能监控到学习状态了，是否真的学习完成也不得而知。

所以建议可以增加关于提示的option。

**Comment by wanglz111** [comment]
> 本人在windows上后台定时运行bat文件，但是这样就不能监控到学习状态了，是否真的学习完成也不得而知。
> 
> 所以建议可以增加关于提示的option。
两个建议
1.bat里面直接写一个弹框，结束后弹一下，自己百度
2.去看一下server酱的api，微信推送，也自己百度

**Comment by jxzzy** [comment]
提示什么啊，学完不管自动关闭了

**Comment by yaohunzhanyue** [comment]
@jxzzy 计划任务后台运行，看不到界面的，你怎么知道脚本是否执行成功呢

**Comment by jxzzy** [comment]
@yaohunzhanyue 
我bat里做了个DOS  在执行完以后写入一个文本文件，开机看文本文件就可以了

**Comment by yaohunzhanyue** [comment]
@jxzzy 好的谢谢，我试试

**Comment by sss521** [comment]
我不建议增加   我运行很正常
希望增加答题功能    用模拟器运行答题功能      我有所有题库  就是不会自动答题

**Comment by wanglz111** [comment]
> @sss521
> 我不建议增加 我运行很正常
> 希望增加答题功能 用模拟器运行答题功能 我有所有题库 就是不会自动答题

你开个新issue，把题库上传一下

**Comment by yaohunzhanyue** [comment]
@sss521 加个option，有需要的就用呗，又不是强制的
