### ISSUE TITLE
活跃时间判断有问题

### ISSUE THREAD

**Issue by Liridice** [Alivon/Panda-Learning#33]
22：37开始学习，也被判断为活跃时间了，导致学习时长不够。

**Comment by Alivon** [comment]
> 22：37开始学习，也被判断为活跃时间了，导致学习时长不够。

‼(•'╻'• )꒳ᵒ꒳ᵎᵎᵎ我看了代码确认是有这个问题，下次更新修复

**Comment by cubobo** [comment]
还有6:00-8:30时段

**Comment by Alivon** [comment]
> 还有6:00-8:30时段

这周末会更新
