### ISSUE TITLE
今天文章数量和时时长都不能学习了

### ISSUE THREAD

**Issue by zzzzzqf** [Alivon/Panda-Learning#330]
视屏可以学，没有挂代理，系统也没动过

**Comment by AthenaCN** [comment]
我也出现了这个问题 估计官方文章链接更新了
估计得更新https://github.com/Alivon/Panda-Learning/blob/master/Source%20Packages/pdlearn/get_links.py

**Comment by bobotoy** [comment]
一样的问题，文章学习在重复进行，但是分数就加不上去，估计是文章列表接口更换了

**Comment by bifu123** [comment]
对，文章一直无限循环地学，但是分数就是加不上去

**Comment by bobotoy** [comment]
也有可能作者默认设置的那个学习栏目文章全部学习完了

**Comment by XxX0000** [comment]
强国更新了

**Comment by bobotoy** [comment]
和更新没关系，网页版框架也没改，应该是文章接口问题

**Comment by wisdog** [comment]
文章挂了

**Comment by XxX0000** [comment]
刚试了一下，我这边暂时还能学

**Comment by zzzzzqf** [comment]
> 刚试了一下，我这边暂时还能学

我刚刚也试了一下 好像又可以了

**Comment by herocspx** [comment]
临时解决方法：修改a_log里的数字为1000

**Comment by AthenaCN** [comment]
现在又恢复正常了

**Comment by zzzzzqf** [comment]
自己又好了，关闭这个issue了

**Comment by bifu123** [comment]
是的




------------------ 原始邮件 ------------------
发件人: "QingFeng Zhang"<notifications@github.com>; 
发送时间: 2019年5月15日(星期三) 下午2:31
收件人: "Alivon/Panda-Learning"<Panda-Learning@noreply.github.com>; 
抄送: "不知道是谁"<415135222@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Alivon/Panda-Learning] 今天文章数量和时时长都不能学习了 (#330)




自己又好了，关闭这个issue了
