### ISSUE TITLE
被检测到了

### ISSUE THREAD

**Issue by insoxin** [Alivon/Panda-Learning#334]
一周内无法获得积分了

**Comment by Alivon** [comment]
说明下环境和使用方法，我的测试号是每天0点国外ip的vps自动跑，比较正常，电报也没用听说检测问题？用过其他方法吗？

**Comment by vay1314** [comment]
使用没被提醒，是不是还用其他软件了？

**Comment by lostinfever** [comment]
我一个IP每天挂接近二十个账号，都没问题

**Comment by yonglianxx** [comment]
每天挂17个账号，无问题

**Comment by 1053203144** [comment]
> 说明下环境和使用方法，我的测试号是每天0点国外IP的VPS自动跑，比较正常，电报也没用听说检测问题？用过其他方法吗？

不更新一下？有时候报错
