### ISSUE TITLE
请问这句话如何理解？

### ISSUE THREAD

**Issue by noway2014** [Alivon/Panda-Learning#35]
readme中说:例如是0的时候可以改成20，12的时候改为30，就是根据上面的数字增加20~30，修改后仍为一个数样式如下36
是不是只会出现0或者12？如果是这两个就修改为20或者30？最多不能超过36？如果其他数字，又如何修改？
用户名没改变，出现不能看文章得分问题，同时，也出现用途停止退出问题。

**Comment by Liridice** [comment]
就是让你把看到的数改成这个数加上20-30之间的随机一个数，比如说你看到的是256，那么随便改成276、278、283、285之类的都可以。
