### ISSUE TITLE
似乎有点问题

### ISSUE THREAD

**Issue by gantrylueng** [Alivon/Panda-Learning#36]
![1](https://user-images.githubusercontent.com/45733548/54500998-4af70680-495d-11e9-8d3a-28bc83977295.JPG)
这已经好几次了，才发上来看看。前面说已经学完了，后面又说还缺多少？为什么卡住了呢？

**Comment by gantrylueng** [comment]
又运行一次，视频似乎没有增加，还是像上次出现了一些error。
![2](https://user-images.githubusercontent.com/45733548/54501621-46345180-4961-11e9-9551-82d686c67af2.JPG)

**Comment by gantrylueng** [comment]
第三次运行，还差5分钟
![3](https://user-images.githubusercontent.com/45733548/54502062-b9d75e00-4963-11e9-8392-066132dffa56.JPG)

**Comment by gantrylueng** [comment]
第四次运行。一打开就说已经学习完了。
![4](https://user-images.githubusercontent.com/45733548/54502123-facf7280-4963-11e9-8dd7-2d8090971dac.JPG)

**Comment by Alivon** [comment]
> 第四次运行。一打开就说已经学习完了。
> ![4](https://user-images.githubusercontent.com/45733548/54502123-facf7280-4963-11e9-8dd7-2d8090971dac.JPG)
尝试安说明修改user/输入的用户名下的log数值

**Comment by Alivon** [comment]
requests timeout是网络原因没有获取到文章视频

**Comment by cz1980** [comment]
学习的时候不是浏览器要开着，一最小化就不得分了，或者被其他窗口挡住就不得分了，怎么还能多线程学习呢。还能开几个窗口一起学习？

**Comment by gantrylueng** [comment]
第一次使用后程序会自动生成 user文件夹，里面包含你的学习历史纪录，当学习文章篇数和视频数出现不加分情况，多半是你变更了用户名，解决办法为进入user文件夹下你用户名文件夹下的log.txt文件，修改上面的数字，例如是0的时候可以改成20，12的时候改为30，就是根据上面的数字增加20~30，修改后仍为一个数样式如下36

已经按要求改好了。改为56。但是，我只有一个用户，也只用过一个用户。就是登录过3次，今天是第4次。窗口没有最小化，挡住的话，基本都是挡住了

**Comment by Alivon** [comment]
> 题的话，不应该，50M的网络，没有下载，没有别的操作，只是在看下载好了的电影。
> 而且似乎不是一次“网络问题”，不会这么巧，10几钟内几次网络问题。

你用的应该是旧版，但是旧版也没有人报告过这个问题，尝试跟新最新版 新版没有窗口了，把log数值再改大点尝试，我自己测试和别人用没有这个问题，有可能是网络或者服务器波动造成的，

**Comment by Alivon** [comment]
> 学习的时候不是浏览器要开着，一最小化就不得分了，或者被其他窗口挡住就不得分了，怎么还能多线程学习呢。还能开几个窗口一起学习？

最新版本没有窗口了

**Comment by gantrylueng** [comment]
原来这样的呀。昨天改了log,56.好了一些。运行一次就视频剩下5分钟
![5](https://user-images.githubusercontent.com/45733548/54575723-2a4bb100-4a30-11e9-916c-bec2e1d13fc9.JPG)

我下载的地方，就是你的官方github处呀。应该是最新的吧，下载的时候直接点击windows没有看到有版本信息？？？？
![6](https://user-images.githubusercontent.com/45733548/54575752-494a4300-4a30-11e9-80ea-1ed83ca4ef43.JPG)
