### ISSUE TITLE
涉嫌违规封号原因基本摸清

### ISSUE THREAD

**Issue by asdqwe111** [Alivon/Panda-Learning#370]
本人因需要，手中大批量的号需要学习。根据被封账号的共同点，得出初步结论！！！！！
用了电脑刷分，又用手机做题的活人账号，全都提示封号了。那些僵尸号，从来不用手机登录的，每天只拿25分完全没事，可以继续使用

**Comment by mr-zl** [comment]
感觉不是这个原因，几个月没做过题了，也没打开过APP依然被封

**Comment by 1053203144** [comment]
> 本人因需要，手中大批量的号需要学习。根据被封账号的共同点，得出初步结论！！！！！
> 用了电脑刷分，又用手机做题的活人账号，全都提示封号了。那些僵尸号，从来不用手机登录的，每天只拿25分完全没事，可以继续使用

乱猜，人家每天都拿满，又是什么操作
