### ISSUE TITLE
封禁规则有毒

### ISSUE THREAD

**Issue by elleys** [Alivon/Panda-Learning#378]
被封7天之后用网页看了一会视频。。。然后就这样了，安全规则是写的有毒吧。。。处在7天封禁期还能二次封禁啊，我怀疑是扫码登录了不同的电脑看了视频
![WeChat Image_20190531185828](https://user-images.githubusercontent.com/1179701/58701809-8f2f6a00-83d6-11e9-86ef-0878f8443262.jpg)

**Comment by noway2014** [comment]
封7天后解封，再网页正常看也这样？

**Comment by elleys** [comment]
> 封7天后解封，再网页正常看也这样？

还在7天封禁期内，就看了一下网页视频

**Comment by secret2030** [comment]
换了个说法吧，应该还是七天，我也是这样。

**Comment by cabble1313** [comment]
我也是这样的情况，封禁期间正常看了下视频，昨天显示封禁，期间无法积分，没有以前显示的时间。我明天就解禁了，不知道会不会无限期封禁。
关键我们单位还要每周统计啊！！！分数都无所谓，主要这个账号得能用。这可咋办？问了客服，说我边看视频边做题目是一心二用。封禁结束后分数不影响，但没想到昨天不显示解禁日期了。问客服也不管事，只说继续关注页面显示。

**Comment by guxd** [comment]
@cabble1313 请问你按期解禁了吗？
