### ISSUE TITLE
获取分数不必打开/points/my-points.html页面，直接get对应的url就可以了

### ISSUE THREAD

**Issue by 2L0b** [Alivon/Panda-Learning#39]

**Comment by Alivon** [comment]
赞一个，下次跟新时候会尝试采用

**Comment by 2L0b** [comment]
> 赞一个，下次跟新时候会尝试采用

钉钉页面可以实现自动登陆，但提交速度不要过快，会弹验证码。
我自己按我的思路修改你的程序了，可以实现无人值守，定时启动，完全不用人干预

**Comment by cxl008** [comment]
@2L0b  可否分享一下代码？

**Comment by 2L0b** [comment]
> @2L0b  可否分享一下代码？

等项目发起人更新吧，思路已经提供了。
感谢这个项目让我重新学起了编程

**Comment by heponextemailnet** [comment]
可以在扫码页面重定向
driver.execute_script('location.href="https://login.dingtalk.com/login/index.htm?goto=https%3A%2F%2Foapi.dingtalk.com%2Fconnect%2Foauth2%2Fsns_authorize%3Fappid%3Ddingoankubyrfkttorhpou%26response_type%3Dcode%26scope%3Dsnsapi_login%26redirect_uri%3Dhttps%3A%2F%2Fpc-api.xuexi.cn%2Fopen%2Fapi%2Fsns%2Fcallback"')
登陆页面js登陆     driver.execute_script('document.getElementById("mobile").value="*****";document.getElementById("pwd").value="*****";document.getElementById("loginBtn").click()')

**Comment by cxl008** [comment]
还是把LS的删了吧，公开了不太好

**Comment by heponextemailnet** [comment]
把url删掉了，剩下的也没什么东西了。。。。

**Comment by 2L0b** [comment]
> 可以在扫码页面重定向
> driver.execute_script('location.href=url)
> 登陆页面js登陆 driver.execute_script('document.getElementById("mobile").value="11111111111";document.getElementById("pwd").value="22222222";document.getElementById("loginBtn").click()')
> 同时建议登陆页面的options.add_argument('blink-settings=imagesEnabled=false') 属性给注释掉，一般登陆页面都比较小，图片的加载速度影响不大，但是要考虑以后是页面否会检测图片加载状态来进行外挂工具筛选

不用，直接打开js插入的账号登录页面url，再用js填充user psw 提交登录。昨天晚上我做了自动登录，get获取积分，完全没有问题，headless之后完全看不到浏览器界面了

**Comment by Alivon** [comment]
> > 可以在扫码页面重定向
> > driver.execute_script('location.href=url)
> > 登陆页面js登陆 driver.execute_script('document.getElementById("mobile").value="11111111111";document.getElementById("pwd").value="22222222";document.getElementById("loginBtn").click()')
> > 同时建议登陆页面的options.add_argument('blink-settings=imagesEnabled=false') 属性给注释掉，一般登陆页面都比较小，图片的加载速度影响不大，但是要考虑以后是页面否会检测图片加载状态来进行外挂工具筛选
> 
> 不用，直接打开js插入的账号登录页面url，再用js填充user psw 提交登录。昨天晚上我做了自动登录，get获取积分，完全没有问题，headless之后完全看不到浏览器界面了

为你点个赞，我现在只有周末极少的空余时间维护更新这个项目，推荐你pull你的代码我周末会更新修改打包

**Comment by Alivon** [comment]
> 可以在扫码页面重定向
> driver.execute_script('location.href=url)
> 登陆页面js登陆 driver.execute_script('document.getElementById("mobile").value="11111111111";document.getElementById("pwd").value="22222222";document.getElementById("loginBtn").click()')
> 同时建议登陆页面的options.add_argument('blink-settings=imagesEnabled=false') 属性给注释掉，一般登陆页面都比较小，图片的加载速度影响不大，但是要考虑以后是页面否会检测图片加载状态来进行外挂工具筛选

谢建议

**Comment by 2L0b** [comment]
> 可以在扫码页面重定向
> driver.execute_script('location.href=url)
> 登陆页面js登陆 driver.execute_script('document.getElementById("mobile").value="11111111111";document.getElementById("pwd").value="22222222";document.getElementById("loginBtn").click()')
> 同时建议登陆页面的options.add_argument('blink-settings=imagesEnabled=false') 属性给注释掉，一般登陆页面都比较小，图片的加载速度影响不大，但是要考虑以后是页面否会检测图片加载状态来进行外挂工具筛选
> 
> 不用，直接打开js插入的账号登录页面url，再用js填充user psw 提交登录。昨天晚上我做了自动登录，get获取积分，完全没有问题，headless之后完全看不到浏览器界面了
> 
> 为你点个赞，我现在只有周末极少的空余时间维护更新这个项目，推荐你pull你的代码我周末会更新修改打包

自动登陆还是不公开的好，容易被偷走恶意盈利。另外我重新设计了程序流程，要大改你的源码，现在只是一个模块一个模块在做

**Comment by Alivon** [comment]
> > 可以在扫码页面重定向
> > driver.execute_script('location.href=url)
> > 登陆页面js登陆 driver.execute_script('document.getElementById("mobile").value="11111111111";document.getElementById("pwd").value="22222222";document.getElementById("loginBtn").click()')
> > 同时建议登陆页面的options.add_argument('blink-settings=imagesEnabled=false') 属性给注释掉，一般登陆页面都比较小，图片的加载速度影响不大，但是要考虑以后是页面否会检测图片加载状态来进行外挂工具筛选
> > 不用，直接打开js插入的账号登录页面url，再用js填充user psw 提交登录。昨天晚上我做了自动登录，get获取积分，完全没有问题，headless之后完全看不到浏览器界面了
> > 为你点个赞，我现在只有周末极少的空余时间维护更新这个项目，推荐你pull你的代码我周末会更新修改打包
> 
> 自动登陆还是不公开的好，容易被偷走恶意盈利。另外我重新设计了程序流程，要大改你的源码，现在只是一个模块一个模块在做

可以的  我最开始是直接记得函数写出来的 后面更新就有点乱了 我也计划把各个 功能封装成类

**Comment by op69qs** [comment]
各位说的都很不错，不过有一点最好改成通过 elem.send_keys()的方式进行模拟输入和按钮点击，这登入界面应该是有行为记录的，使用js控制风险比较大

**Comment by 2L0b** [comment]
> 各位说的都很不错，不过有一点最好改成通过 elem.send_keys()的方式进行模拟输入和按钮点击，这登入界面应该是有行为记录的，使用js控制风险比较大
> 对了useragent也要自定义下 默认里面有个headless在里面太招摇了

因为这个登陆页面用selenium不能sendkey，所以只能通过通过执行js控制
header带headless 确实有风险

**Comment by op69qs** [comment]
sendkey是可以实现的 我都已经在用了
