### ISSUE TITLE
文章和阅读加不满的情况

### ISSUE THREAD

**Issue by zayvion** [Alivon/Panda-Learning#401]
这两天出现文章加不满和阅读时间不增加的情况，一直在刷不停止的那种，大家有类得的情况吗？

**Comment by FLASH023** [comment]
正常操作，一切正常。   没用熊猫之类的。
正规阅读学习是可以的。

**Comment by rjliulei** [comment]
出现了，应该是网站又升级了。。。

**Comment by skyfire1945** [comment]
网站的问题应该是 在 电脑端学习不加 阅读积分

**Comment by jzmswe** [comment]
> 网站的问题应该是 在 电脑端学习不加 阅读积分

加，但文章时长要4分钟一个才行，最后一个要安卓模拟才行。

**Comment by jzmswe** [comment]
> 正常操作，一切正常。 没用熊猫之类的。
> 正规阅读学习是可以的。

你不用熊猫，还每天上这里发帖，请问是什么心态？能否说说。

**Comment by FLASH023** [comment]
> > 正常操作，一切正常。 没用熊猫之类的。
> > 正规阅读学习是可以的。
> 
> 你不用熊猫，还每天上这里发帖，请问是什么心态？能否说说。

因为我不是DY，对学习积分没有要求。但是给同事推荐过这个东西，导致同事被封号了。
另外我做过很多年程序，阅读了熊猫的代码。
其实要检测封掉熊猫，一招就可以了。   那就是熊猫使用了钉钉的帐号密码登陆接口，而强国只有扫码接口。凡是使用钉钉的帐号密码接口登陆的，绝对不会错杀。
另外熊猫是给chrome浏览器穿了马甲，它的数据请求文件头异常，轻松被检测到。

这是开源的代码社区，只是共享大家的看法而已。
