### ISSUE TITLE
一天多才在VPS上正常运行，居然提示号码或密码错误？？Boooooom

### ISSUE THREAD

**Issue by dyf1989314** [Alivon/Panda-Learning#422]
一天多才在VPS上正常运行，居然提示号码或密码错误？？
手机登录没有问题    
是脚本出问题了么？
大佬快更新吧   跪谢~~~
Boooooom

**Comment by dyf1989314** [comment]
原来是钉钉的问题  已经解决了 ~

**Comment by Colwzq** [comment]
> 原来是钉钉的问题 已经解决了 ~

具体是啥问题 我也碰到了这个情况
