### ISSUE TITLE
我保存有20190717某大神公布的代码，可绕过那什么

### ISSUE THREAD

**Issue by jzmswe** [Alivon/Panda-Learning#448]
如果有朋友能用python生成熊猫.exe，我可以贴出这段代码，或者私下发邮箱也可以。
生成后，可以上传网盘后，在这里贴出下载链接。也可以私下发我邮箱。
有意者，请回帖。
绕过后，就可以加入系统任务计划程序了，这样就省事很多。
使用这段代码后，前几天使之弹出窗口，输入那什么的代码，就没必要使用了。

**Comment by 424032354** [comment]
之前试过生成，但就是有各种问题不能运行，代码能私发一下？

**Comment by hbqjb** [comment]
请将代码发至hbqjb@126.com，生成后发给您！谢谢！！

**Comment by hbqjb** [comment]
此外，我想在“检测到文章数量分数已满,退出学习”及视频“退出学习”之后，再分别加入学习14条的循环学习代码，以每条15秒左右学完，以便完成“点点通”的积分。不知有高手指点没有？

**Comment by jzmswe** [comment]
> 请将代码发至[hbqjb@126.com](mailto:hbqjb@126.com)，生成后发给您！谢谢！！

已发，收到后会看到我的邮箱地址，我不用点点通，生成后你测试如果可用，直接发给我就行。

**Comment by jzmswe** [comment]
> 之前试过生成，但就是有各种问题不能运行，代码能私发一下？

你的邮箱？

**Comment by 424032354** [comment]
邮箱：jc32048314shang@163.com

**Comment by jzmswe** [comment]
> 邮箱：[jc32048314shang@163.com](mailto:jc32048314shang@163.com)

**Comment by jzmswe** [comment]
> 邮箱：[jc32048314shang@163.com](mailto:jc32048314shang@163.com)

jc=警察？呵呵，也行吧，已发。

**Comment by 424032354** [comment]
jc="教材"的意思

**Comment by 424032354** [comment]
我打包后运行，报错cannot import name 'mydriver' from 'pdlearn' ，问题是这个文件 我是有的

**Comment by 888hou** [comment]
888hou@gmail.com分享下

**Comment by a153910** [comment]
15957904551@163.com  分享一下 谢谢
