### ISSUE TITLE
西方人是这样啦，什么时候放弃过对别人的偏见和霸权主义思想吗？

### ISSUE THREAD

**Issue by ChenShihuan** [Alivon/Panda-Learning#45]
不止gayhub不是白莲花，别的也不是，只不过程度不同而已。不仅仅对中国，还有别的他们想干涉的国家都是这样。还记得推特对委内瑞拉总统的主页的取消认证和“临时总统”的主页加认证的事情吗？

**Comment by Alivon** [comment]
这是程序员社区请勿讨论政治相关议题。

**Comment by ChenShihuan** [comment]
不好意思，回复错了，应该回复另外一个项目下面的
