### ISSUE TITLE
您好  为什么我下载不了win版本呢

### ISSUE THREAD

**Issue by doubleai** [Alivon/Panda-Learning#49]
麻烦panda帮我看看 为什么下载不了 连续两天下载了

**Comment by Alivon** [comment]
可能是你网络问题，请自行搜索包括但不限于  "github下载慢" 等问题

**Comment by doubleai** [comment]
> 可能是你网络问题，请自行搜索包括但不限于  "github下载慢" 等问题
OK 我再去试试 麻烦了
