### ISSUE TITLE
win7应该下载那个版本？

### ISSUE THREAD

**Issue by noway2014** [Alivon/Panda-Learning#5]

**Comment by Alivon** [comment]
下载windows版本即可

**Comment by noway2014** [comment]
win版本在win7无法使用。提示不兼容,安装附带的那个vc也一样，希望解决

**Comment by Alivon** [comment]
> win版本在win7无法使用。提示不兼容,安装附带的那个vc也一样，希望解决

会解决

**Comment by Alivon** [comment]
> win版本在win7无法使用。提示不兼容,安装附带的那个vc也一样，希望解决

会解决 ，请随时关注

**Comment by Alivon** [comment]
> 赢得版本在WIN7无法使用。提示不兼容，安装附带的那个VC也一样，希望解决

已支持win7 32位系统
