### ISSUE TITLE
登录二维码不显示

### ISSUE THREAD

**Issue by LarryLi-cn** [Alivon/Panda-Learning#506]
一直用的好好的，最近不知道怎么了，登录用的二维码一直刷不出来，望大神解决。

**Comment by zhu1979** [comment]
请看 #503

**Comment by LarryLi-cn** [comment]
修改完成后，使用pyinstaller -F Mydriver.py打包成exe吗？

**Comment by danjuanyang** [comment]
同状况，我的只是弹出浏览器时候，不自动移动到二维码区域，这个刷新一下网页可以解决，不知道你是不是这个状况

**Comment by LarryLi-cn** [comment]
我的直接不显示，看了应该是#503中所说问题，但是我修改打包之后程序闪退，但是使用#503评论区的https://pan.baidu.com/s/13GXMmMgJaWC5Y8TZmuKjoA 提取码: bu5s这个可以用。也是如你所说，不自动移动到二维码区域，但是无所谓啦~  能用就行
