### ISSUE TITLE
最新版本在win7专业版64位环境下报错

### ISSUE THREAD

**Issue by abcdefg2019** [Alivon/Panda-Learning#53]
![1](https://user-images.githubusercontent.com/48745318/54663687-1af66180-4b1d-11e9-9af1-ad809238d344.jpg)
![2](https://user-images.githubusercontent.com/48745318/54663816-73c5fa00-4b1d-11e9-8ec3-ffe6ea75bab8.jpg)

**Comment by abcdefg2019** [comment]
还请大咖帮忙解决啊

**Comment by Alivon** [comment]
> 还请大咖帮忙解决啊

周末我会排查更新修复
