### ISSUE TITLE
win10 64bit, 单击 pandalearn.py 控制台闪现闪退

### ISSUE THREAD

**Issue by harrydengchao** [Alivon/Panda-Learning#62]
win10 64bit, 单击 pandalearn.py 控制台闪现闪退。 我需要如何解决呢

**Comment by Alivon** [comment]
> win10 64bit, 单击 pandalearn.py 控制台闪现闪退。 我需要如何解决呢

未遇到这种情况，win64应该是很稳定的版本

**Comment by harrydengchao** [comment]
@Alivon  很抱歉！我点的是根目录下的 `pandalearn.py` ，逃...。   所以，win64是很稳定的。很赞
