### ISSUE TITLE
默认不要用headless模式吧

### ISSUE THREAD

**Issue by smilingpoplar** [Alivon/Panda-Learning#63]
headless模式的[User-Agent等特征](https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html)可能被检测到

**Comment by Alivon** [comment]
> headless模式的[User-Agent等特征](https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html)可能被检测到

马上的跟新会增加选择是否headless
