### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Marvel0914** [Alivon/Panda-Learning#65]
能帮忙看下什么原因吗?

**Comment by yzy806806** [comment]
我也遇到了同样的问题，会不会是网页那边接口改了？

**Comment by Melody999** [comment]
局域网两台电脑，一台正常一台提示无法连接

**Comment by Alivon** [comment]
> 能帮忙看下什么原因吗?

我感觉是跟服务器连接已经丢失，但是还在执行链连接才能执行的任务，会返回该提示

**Comment by Marvel0914** [comment]
> > 能帮忙看下什么原因吗？
> 
> 我感觉是跟服务器连接已经丢失，但是还在执行链连接才能执行的任务，会返回该提示

请问应该如何解决?东西都是正常的,就是在CMD里面无法连接。
