### ISSUE TITLE
网页版不让登陆了

### ISSUE THREAD

**Issue by tefiszx** [Alivon/Panda-Learning#8]
2019年3月15日。早上登陆学习网页，提示系统繁忙，拒绝登陆了。学习强国我用了一段时间，感觉还是不错了。信息量能再大点就好了。

**Comment by Alivon** [comment]
我刚才用手机打开，发现没有异常，应该是网站服务器或者你的网络开了小差，
黑暗与正义说的太过了，学习强国是一个非常好的app，至少推广方式有些极端。
