### ISSUE TITLE
win10的安全中心报毒了。不知道为什么会打开两个chrome窗口。

### ISSUE THREAD

**Issue by LevineWoo** [Alivon/Panda-Learning#9]
win10的安全中心报毒了。不知道为什么会打开两个chrome窗口。

**Comment by Alivon** [comment]
误报，源码是开放的请放心使用。
两个Chrome是两个独立线程并发学习，加快积分获取时间。

**Comment by LevineWoo** [comment]
> 误报，源码是开放的请放心使用。
> 两个Chrome是两个独立线程并发学习，加快积分获取时间。

就是说两个chrome可以登录同一个账户来同步学习是吗？
另外求捐赠通道以鼓励加快开发订阅收藏评论分享答题功能。

**Comment by Alivon** [comment]
> > 误报，源码是开放的请放心使用。
> > 两个Chrome是两个独立线程并发学习，加快积分获取时间。
> 
> 就是说两个chrome可以登录同一个账户来同步学习是吗？
> 另外求捐赠通道以鼓励加快开发订阅收藏评论分享答题功能。

是的  一个程序会开两个chrome来加快学习积分获取，程序可以多开，捐赠以后考虑，tanks
